version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampleDb
      MYSQL_USER: flaskapp
      MYSQL_PASSWORD: flaskapp
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  workprofile:
    build: ..
    environment:
      DB_HOST: mysql
      DB_USER: flaskapp
      DB_PASS: flaskapp
      DB_NAME: exampleDb
    depends_on:
      - mysql
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - workprofile
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:

volumes:
  db_data:
